#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDfrljCVuQ+BuVkZN0bWMmFdk1LXlrX85jvLJgJRqnFh yk88@ukr.net
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/hVPz+HvPbkr5NHfIueG+kg9H3nCi+Uagjo57u1c1Q yk88@ukr.net
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - apt-get update -y
  - curl https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
  - chown cluster:cluster /etc/rancher/k3s/k3s.yaml
  - chown cluster:cluster /var/lib/rancher/k3s/server/node-token
